In [ ]:
import pandas as pd

print("Notebook working 🚀")

In [ ]:
import pandas as pd
print("Pandas working")

Pandas working

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import pandas as pd

data = {
    "players": ["virat", "Rohit", "sehwag", "dhoni", "virat", "Rohit", "sehwag", "dhoni"],
    "matches": [100, 200, 300, 400, 100, 200, 300, 400],
    "runs": [154, 200, 123, 257, 309, 198, 171, 120],
    "Balls": [50, 100, 120, 120, 150, 80, 120, 100]
}

ipl = pd.DataFrame(data)

print("Original Data:")
display(ipl)

# 1. Find strike rate of each player
ipl["Strike_Rate"] = (ipl["runs"] / ipl["Balls"]) * 100

print("1. Strike Rate of Each Player:")
display(ipl[["players", "runs", "Balls", "Strike_Rate"]])

# 2. Show only matches where Virat scored more than 150
virat_150 = ipl[(ipl["players"] == "virat") & (ipl["runs"] > 150)]

print("2. Virat scored more than 150:")
display(virat_150)

# 3. Show total runs scored by player and highest score by player
summary = ipl.groupby("players").agg(
    Total_Runs=("runs", "sum"),
    Highest_Score=("runs", "max")
)

print("3. Total Runs and Highest Score by Player:")
display(summary)

Original Data:

  players  matches  runs  Balls
0   virat      100   154     50
1   Rohit      200   200    100
2  sehwag      300   123    120
3   dhoni      400   257    120
4   virat      100   309    150
5   Rohit      200   198     80
6  sehwag      300   171    120
7   dhoni      400   120    100

1. Strike Rate of Each Player:

  players  runs  Balls  Strike_Rate
0   virat   154     50   308.000000
1   Rohit   200    100   200.000000
2  sehwag   123    120   102.500000
3   dhoni   257    120   214.166667
4   virat   309    150   206.000000
5   Rohit   198     80   247.500000
6  sehwag   171    120   142.500000
7   dhoni   120    100   120.000000

2. Virat scored more than 150:

  players  matches  runs  Balls  Strike_Rate
0   virat      100   154     50        308.0
4   virat      100   309    150        206.0

3. Total Runs and Highest Score by Player:

         Total_Runs  Highest_Score
players
Rohit           398            200
dhoni           377            257
sehwag          294            171
virat           463            309

In [5]:
df = pd.DataFrame(data)

grp = df.groupby("players")["runs"].sum()

print(grp)

players
Rohit     398
dhoni     377
sehwag    294
virat     463
Name: runs, dtype: int64

In [1]:
import pandas as pd

df=pd.DataFrame({
    "Name":["Rahul","Joy","Kumar","Mahi","Jhanvi","Shubham","Priya","Anit"],
    "age":[25,30,35,40,50,21,43,45],
    "city":["New York","Los Angeles","Chicago","Houston","hongkong","delhi","mumbai","kolkata"],
    "sal":[50000,60000,70000,80000,30000,32000,45000,870000],
    "Experience":[2,5,7,10,15,1,8,20],
    "Department":["IT","HR","Finance","IT","HR","Finance","IT","HR"]
})

In [2]:
print(df[["sal","Name"]])

      sal     Name
0   50000    Rahul
1   60000      Joy
2   70000    Kumar
3   80000     Mahi
4   30000   Jhanvi
5   32000  Shubham
6   45000    Priya
7  870000     Anit

In [3]:
print(df[df["age"]>40])

     Name  age      city     sal  Experience Department
4  Jhanvi   50  hongkong   30000          15         HR
6   Priya   43    mumbai   45000           8         IT
7    Anit   45   kolkata  870000          20         HR

In [4]:
print(df.iloc[2:5])

     Name  age      city    sal  Experience Department
2   Kumar   35   Chicago  70000           7    Finance
3    Mahi   40   Houston  80000          10         IT
4  Jhanvi   50  hongkong  30000          15         HR

In [5]:
print(df.loc[0:3, ["Name","Department"]])

    Name Department
0  Rahul         IT
1    Joy         HR
2  Kumar    Finance
3   Mahi         IT

In [6]:
print(df.loc[0:3, ["Name","Department"]])

    Name Department
0  Rahul         IT
1    Joy         HR
2  Kumar    Finance
3   Mahi         IT

In [7]:
print(df.loc[0:3, ["Name","Department"]])

    Name Department
0  Rahul         IT
1    Joy         HR
2  Kumar    Finance
3   Mahi         IT

In [8]:
print(df[df["Department"]=="IT"]["Name"])

0    Rahul
3     Mahi
6    Priya
Name: Name, dtype: object

In [9]:
print(df.iloc[-3:,0:2])

      Name  age
5  Shubham   21
6    Priya   43
7     Anit   45

In [10]:
print(df[(df["sal"]>=60000) & (df["sal"]<=80000)][["Name","city"]])

    Name         city
1    Joy  Los Angeles
2  Kumar      Chicago
3   Mahi      Houston

In [ ]:
import numpy as np
import pandas as pd
age = [25, 30, 35, 40, 50, 21, 43, 45]
Name= ["Rahul", "Joy", "Kumar", "Mahi", "Jhanvi", "Shubham", "Priya", "Anit"]
city = ["New York", "Los Angeles", "Chicago", "Houston", "hongkong", "delhi", "mumbai", "kolkata"]
sal = [50000, 60000, 70000, 80000, 30000, 32000, 45000, 870000]
Experience = [2, 5, 7, 10, 15, 1, 8, 20]
department = ["IT", "HR", "Finance", "IT", "HR", "Finance", "IT", "HR"]
data = {"age": age, "city": city, "sal": sal, "Experience": Experience}
df = pd.DataFrame(data)

df.isna().sum()
df.notna()
df.notnull().sum()
df.notnull().mean()*100
df[df.isna().any(axis=1)]#atleast one missing val in any col
df[df.isna().all(axis=1)]#all row missing val
df[df["age"].isna()]#missing val in age col
df.dropna()#drop all rows with missing val
df.dropna(subset=["age"])#drop rows with missing val in age col
df.dropna(subset=["age","Experience","city"])
df
df.dropna(axis=1)#drop col with missing val
df.dropna(axis=0)#drop row with missing val
df.dropna(axis=0,thresh=2)#drop row with less than 2 non-null values
df2=df.dropna(axis=1)#drop col with missing val and assign to new df
df["Experience"].fillna(0)#fill missing val in Experience col with 0
#inplace=True will modify the original df
df["city"].fillna("Unknown")#fill missing val in city col with "Unknown"
df.fillna({ "Experience": 0, "city": "Unknown" })#fill missing val in Experience col with 0 and city col with "Unknown"


#filling empty values statistically
df["age"].fillna(df["age"].mean())
df["age"].fillna(df["age"].median())
df["age"].fillna(df["age"].mode()[0])#It fills missing values (NaN) in the age column with the most frequently occurring age.
df.replace("Finance","FIna",inplace=True)
df
data=({
    "Student": ["Alice", "Bob", "Charlie", "David"],
    "Math": [85, 90, 78,np.nan, 92],
    "Science": [88, 92, 80,np.nan,95],    
     "English": [90,np.nan, 85, 82, 88],
     "Sanskrit": [80, 87, 85, 90,np.nan,45],
     "Attendance": [95, 90, np.nan,85, 98]
     })
# count missing val
# fill all the missing val in maths with the mean value without using mean function
# in english fill the missing values with 0
# verify whether your data having any missing values or not 
# fill the nan values in attendance coloumns using mean value
# remove the row more than 2 nan values

#answers
# 1.print(df.isna().sum())
# 2.maths_mean = df["maths"].sum() / df["maths"].count()
# df["maths"] = df["maths"].fillna(maths_mean)
# print(df["maths"])
# 3.df["English"] = df["English"].fillna(0)
# 4.print(df.isna().sum())
# 5.attendance_mean = df["Attendance"].sum() / df["Attendance"].count()
# df["Attendance"] = df["Attendance"].fillna(attendance_mean)
# print(df["Attendance"])
# 6.df2 = df[df.isna().sum(axis=1) <= 2]
# print(df2)

In [ ]:
import numpy as np
import pandas as pd
CustomerName=["Rahul","Joy","Kumar","Mahi","Jhanvi","Shubham","Priya","Anit"]
Age=[25,30,35,40,50,21,43,45]
City=["New York","Los Angeles","Chicago","Houston","hongkong","delhi","mumbai","kolkata"]
data={"CustomerName":CustomerName,"Age":Age,"City":City}

In [10]:
#pandas using for clacculating mean 
import pandas as pd
Salary=[110,70,86,65,70,80,90,100,5000]
df=pd.DataFrame({"Salary":Salary})
mean_sal=df["Salary"].mean()
print("Mean Salary:", mean_sal)

Mean Salary: 630.1111111111111

In [ ]:
import numpy as np
sal_num=[110,70,86,65,70,80,90,100]#here we removed the outlier value 5000 for accurate mean calculation or skwed value

print(np.mean(sal_num))
print(np.mean(Salary))

83.875
630.1111111111111

### when to use mean 
1,when the data is distributedd normally(bell curve)
2,no extreme values or extreme outliers
3,the data should b continuos
### when u shouldn't use mean 
1,when data is skewed
2,when outliers exist 
## median-median is the middle value when data is sorted 
#### 1,sort the data
#### 2,if odd count-middle value will be the median
#### 3, if even cout-avg of two middle val will be median

In [19]:
marks=[110,70,86,65,70,80,90,100,5000] #skwed data or outlier data
mrks=[110,70,86,65,70,80,90,100] #removing outlier value for accurate mean calculation
def calculate_median(data):
    sorted_data = sorted(data)#ascending order
    n = len(sorted_data)
    if n % 2 == 0:
        return (sorted_data[n//2 - 1] + sorted_data[n//2]) / 2
    else:
        return sorted_data[n//2]
median_marks = calculate_median(marks)
print("Manual_Median Marks:", median_marks)
print("numpy median:", np.median(mrks))
#calculating median using Numpy
print("Median with outlier:",np.median(marks))
print("Median without outlier:",np.median(mrks))

Manual_Median Marks: 86
numpy median: 83.0
Median with outlier: 86.0
Median without outlier: 83.0

In [ ]:
#calculating median using pandas 
data=pd.DataFrame({"Marks":marks})
skwdmdn=data["Marks"].median()
print("pandas median with outlier:",skwdmdn)

### Mode
### mode is the most frequent value in dataset.its a measure of central tendency that wrks for categorical data..

In [22]:
from scipy import stats
from collections import Counter

scores = [85, 90, 92, 85, 88, 95, 90, 85, 88]

def cal_mode(data):
    counter = Counter(data)
    maxdata = max(counter.values())
    modes = [k for k, v in counter.items() if v == maxdata]
    return modes, maxdata

manual_mode, frequency = cal_mode(scores)

print("Manual Mode:", manual_mode)
print("Frequency of Manual Mode:", frequency)

Manual Mode: [85]
Frequency of Manual Mode: 3

<!-- types of modes
unimode-(one mode val)
bimode-(2 mode val)
multimode-(more than 2 mode val)
nomode-(unique)
 -->

### (very imp for ds)Label Encoding
### this is the way to teach machines how to read categories

In [ ]:
data=["Red", "Blue", "Green", "Red","Yellow", "Blue", "Red"]#list of colors and ml not b able to read this
encoded_data=[0,1,2,0,3,1,0]#here we are encoding the categorical data into numerical data for ml model to read and understand

## types of categorical data
# 1,nominaldata:Nominal data consists of categories without any natural order or ranking.(not cmpred )
# 2,ordinaldata:(meaning ful order)

In [23]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [24]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

data = pd.DataFrame({
    "Colors": ["Red", "Blue", "Green", "Red", "Yellow", "Blue", "Red"],
    "Sizes": ["Small", "Medium", "Large", "Small", "Medium", "Large", "Small"]
})

print(data)

   Colors   Sizes
0     Red   Small
1    Blue  Medium
2   Green   Large
3     Red   Small
4  Yellow  Medium
5    Blue   Large
6     Red   Small

In [ ]:
le=LabelEncoder()
data["Encoded_Colors"]=le.fit_transform(data["Colors"])
# # data["Colors"]=le.fit_transform(data["Colors"])
# data["Sizes"]=le.fit_transform(data["Sizes"])
# print("After label encoding:")
# print(data)
le.classes_#this will show the unique classes in the Colors column and their corresponding encoded values. In this case, it will output: array(['Blue', 'Green', 'Red', 'Yellow'], dtype=object) which indicates that "Blue" is encoded as 0, "Green" as 1, "Red" as 2, and "Yellow" as 3.
print(dict(zip(le.classes_,range(len(le.classes_)))))#this will create a dictionary mapping each unique class in the Colors column to its corresponding encoded value. The output will be: {'Blue': 0, 'Green': 1, 'Red': 2, 'Yellow': 3}, which indicates that "Blue" is encoded as 0, "Green" as 1, "Red" as 2, and "Yellow" as 3.
data

{np.int64(0): 0, np.int64(1): 1, np.int64(2): 2, np.int64(3): 3}

   Colors  Sizes  Encoded_Colors
0       2      2               2
1       0      1               0
2       1      0               1
3       2      2               2
4       3      1               3
5       0      0               0
6       2      2               2

In [ ]:
d1=["A","B","C","D"]
d2=[1,2,3,4]
print(dict(zip(d2,d1)))#here we are creating a dictionary by zipping two lists together, where the keys are from d2 and the values are from d1. The resulting dictionary will be {1: 'A', 2: 'B', 3: 'C', 4: 'D'}.

{1: 'A', 2: 'B', 3: 'C', 4: 'D'}

In [36]:
fruits=["Apple","Banana","Orange"]
le=LabelEncoder()
enc_fruits=le.fit_transform(fruits)
print("Encoded Fruits:",enc_fruits.tolist())

Encoded Fruits: [0, 1, 2]

## onehotencoding
one hot encoding creates binary columns for each category

In [37]:
myData=pd.DataFrame({"color":["Red","Blue","Green","Blue","Red","Magenta","Magenta","Yellow"],
                     "size":["Small","Medium","Large","Medium","Small","Large","Large","Medium"],
                     "price":[10,20,30,20,10,15,25,20]})
myData

#Pandas For OnHotENcoding 

datas=pd.get_dummies(myData,columns=["color","size"],prefix=["col","siz"])
datas

,price,col_Blue,col_Green,col_Magenta,col_Red,col_Yellow,siz_Large,siz_Medium,siz_Small
0,10,False,False,False,True,False,False,False,True
1,20,True,False,False,False,False,False,True,False
2,30,False,True,False,False,False,True,False,False
3,20,True,False,False,False,False,False,True,False
4,10,False,False,False,True,False,False,False,True
5,15,False,False,True,False,False,True,False,False
6,25,False,False,True,False,False,True,False,False
7,20,False,False,False,False,True,False,True,False

In [38]:
import pandas as pd

data = pd.DataFrame({
    "Fruits": ["Apple", "Banana", "Orange", "Apple", "Banana"],
    "size": ["Small", "Medium", "Large", "Small", "Medium"],
    "price": [10, 20, 30, 10, 20]
})

encoded_data = pd.get_dummies(
    data,
    columns=["Fruits", "size"],
    prefix=["Frt", "Sz"],
    dtype=int
)

print(encoded_data)

   price  Frt_Apple  Frt_Banana  Frt_Orange  Sz_Large  Sz_Medium  Sz_Small
0     10          1           0           0         0          0         1
1     20          0           1           0         0          1         0
2     30          0           0           1         1          0         0
3     10          1           0           0         0          0         1
4     20          0           1           0         0          1         0

In [39]:
#Pandas For OnHotENcoding 

datas=pd.get_dummies(myData,columns=["color","size"],prefix=["col","siz"])
datas

data=pd.DataFrame({
    "Fruits":["Apple","Banana","Orange","Apple","Banana"],
    "Size":["Small","Medium","Large","Small","Medium"],
    "Price":[10,20,30,10,20]
})
data

#### Price - Price is the numeric value that the ML Algo can understand 
#### Size  - That is in text format that cant be understood by the ML algo 
#### Fruits - That is in Text format that also cant be understood by the ML Algos 

encData=pd.get_dummies(data,columns=["Fruits"],prefix=["Frt"],dtype=int)
encData
encdata2=pd.get_dummies(data,columns=["Size"],prefix=["Sz"],dtype=int)
encdata2
encode_data=pd.get_dummies(data,columns=["Fruits","Size"],prefix=["Frt","Sz"],dtype=int)
encode_data
from sklearn.preprocessing import OneHotEncoder

obj=OneHotEncoder()
data=pd.DataFrame({
    "Fruits":["Apple","Banana","Orange","Apple","Banana"],
    "Size":["Small","Medium","Large","Small","Medium"],
    "Price":[10,20,30,10,20]
})


# Here we have encoded the data using Onehotencoder 
encoded_data=obj.fit_transform(data[["Fruits","Size"]])

encoded_data.toarray() # here we are getting an array in encoded format 


# here we are extratcing  the fearure names or the newly created columns after encoding the data
feature_names=obj.get_feature_names_out(["Fruits","Size"])
feature_names

final_data=pd.DataFrame(encoded_data.toarray(),columns=feature_names)
final_data["New Price"]=data["Price"]
final_data

,Fruits_Apple,Fruits_Banana,Fruits_Orange,Size_Large,Size_Medium,Size_Small,New Price
0,1.0,0.0,0.0,0.0,0.0,1.0,10
1,0.0,1.0,0.0,0.0,1.0,0.0,20
2,0.0,0.0,1.0,1.0,0.0,0.0,30
3,1.0,0.0,0.0,0.0,0.0,1.0,10
4,0.0,1.0,0.0,0.0,1.0,0.0,20