In [ ]:
import pandas as pd

print("Notebook working 🚀")

In [ ]:
import pandas as pd
print("Pandas working")

Pandas working

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import pandas as pd

data = {
    "players": ["virat", "Rohit", "sehwag", "dhoni", "virat", "Rohit", "sehwag", "dhoni"],
    "matches": [100, 200, 300, 400, 100, 200, 300, 400],
    "runs": [154, 200, 123, 257, 309, 198, 171, 120],
    "Balls": [50, 100, 120, 120, 150, 80, 120, 100]
}

ipl = pd.DataFrame(data)

print("Original Data:")
display(ipl)

# 1. Find strike rate of each player
ipl["Strike_Rate"] = (ipl["runs"] / ipl["Balls"]) * 100

print("1. Strike Rate of Each Player:")
display(ipl[["players", "runs", "Balls", "Strike_Rate"]])

# 2. Show only matches where Virat scored more than 150
virat_150 = ipl[(ipl["players"] == "virat") & (ipl["runs"] > 150)]

print("2. Virat scored more than 150:")
display(virat_150)

# 3. Show total runs scored by player and highest score by player
summary = ipl.groupby("players").agg(
    Total_Runs=("runs", "sum"),
    Highest_Score=("runs", "max")
)

print("3. Total Runs and Highest Score by Player:")
display(summary)

Original Data:

  players  matches  runs  Balls
0   virat      100   154     50
1   Rohit      200   200    100
2  sehwag      300   123    120
3   dhoni      400   257    120
4   virat      100   309    150
5   Rohit      200   198     80
6  sehwag      300   171    120
7   dhoni      400   120    100

1. Strike Rate of Each Player:

  players  runs  Balls  Strike_Rate
0   virat   154     50   308.000000
1   Rohit   200    100   200.000000
2  sehwag   123    120   102.500000
3   dhoni   257    120   214.166667
4   virat   309    150   206.000000
5   Rohit   198     80   247.500000
6  sehwag   171    120   142.500000
7   dhoni   120    100   120.000000

2. Virat scored more than 150:

  players  matches  runs  Balls  Strike_Rate
0   virat      100   154     50        308.0
4   virat      100   309    150        206.0

3. Total Runs and Highest Score by Player:

         Total_Runs  Highest_Score
players
Rohit           398            200
dhoni           377            257
sehwag          294            171
virat           463            309

In [5]:
df = pd.DataFrame(data)

grp = df.groupby("players")["runs"].sum()

print(grp)

players
Rohit     398
dhoni     377
sehwag    294
virat     463
Name: runs, dtype: int64